app: web-proyecto-serverless
org: jeffer24
#console: true

service: serverless-user-module

frameworkVersion: '3'

#plugins:
  #- serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: "us-east-1"
  stage: ${opt:stage}

  apiGateway:
    request:
      schemas:
        user-input-model:
          name: UsuarioInputModel
          schema: ${file(infraestructure/handlers/schemas/usuarios-schema.json)}
          description: "Validacion de los datos del usuario"

functions:
  getUsuarios:
    handler: infraestructure/handlers/usuarios-handler.getUsuarios
    events:
      - http:
          path: usuarios
          method: get
          #cors: true
          #authorizer: aws_iam
  createUsuario:
    handler: infraestructure/handlers/usuarios-handler.createUsuario
    events:
      - http:
          path: usuarios
          method: post
          request:
            schemas:
              application/json: ${file(infraestructure/handlers/schemas/usuarios-schema.json)}

  updateUsuario:
    handler: infraestructure/handlers/usuarios-handler.updateUsuario
    events:
      - http:
          path: usuarios/{id}
          method: put
          request:
            schemas:
              application/json: ${file(infraestructure/handlers/schemas/usuarios-schema.json)}
  deleteUsuario:
    handler: infraestructure/handlers/usuarios-handler.deleteUsuario
    events:
      - http:
          path: usuarios/{id}
          method: delete  
  getDetailUsuario:
    handler: infraestructure/handlers/usuarios-handler.getDetailUsuario
    events:
      - http:
          path: usuarios/{id}
          method: get